# Generated by Django 6.0.3 on 2026-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(help_text='Used for identifying the tenant db', max_length=100, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=255)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.IntegerField(default=5432)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_restaurant',
            },
        ),
    ]
