# Generated by Django 5.2.12 on 2026-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Hex code for primary brand color', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(default='#f59e0b', help_text='Hex code for secondary brand color', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='db_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='subdomain',
            field=models.CharField(help_text="Used for routing e.g., 'subdomain.saas.com'", max_length=50, unique=True),
        ),
    ]
